name = "fundamental_constants"
version = "1.11"
license = "MIT"
author = "Vincent MAGNIN"
maintainer = "https://github.com/chemical-accuracy"
copyright = "2021 Vincent MAGNIN"


[library]
source-dir="."

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

